[app]
ns="ShareCodeCommit"
stage="Dev"

[aws]
region="ap-northeast-2"

[repository]
name="share-test" # Codecommit repository name to share

[share]
account="" # Account to share the repository with
expiryDate="2099-03-01" # RFC3339 format, 2024-03-01
